services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ../uploads:/server/uploads
    develop:
      watch:
        - action: rebuild
          path: ./server/
          target: /server
        - action: rebuild
          path: ./server/poetry.lock
    env_file:
      - ./server/.env
    networks:
      - network

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL:  http://localhost:8000/api/v1
    env_file:
      - ./web/.env
    depends_on:
      - server
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - network

networks:
    network:
        driver: bridge
